# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63ommon.proto\"\x06\n\x04nullb\x06proto3')
)




_NULL = _descriptor.Descriptor(
  name='null',
  full_name='null',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=22,
)

DESCRIPTOR.message_types_by_name['null'] = _NULL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

null = _reflection.GeneratedProtocolMessageType('null', (_message.Message,), dict(
  DESCRIPTOR = _NULL,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:null)
  ))
_sym_db.RegisterMessage(null)


# @@protoc_insertion_point(module_scope)
