# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: label_distribution.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='label_distribution.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x18label_distribution.proto\x1a\x0c\x63ommon.proto\"U\n\x05label\x12\x10\n\x08label_id\x18\x01 \x01(\x05\x12\x12\n\nis_unicast\x18\x02 \x01(\x08\x12\x12\n\nservice_id\x18\x03 \x01(\t\x12\x12\n\nlanzone_id\x18\x04 \x01(\t2\x90\x01\n\x12label_distribution\x12\'\n\x12rpc_deposit_labels\x12\x06.label\x1a\x05.null\"\x00(\x01\x12(\n\x13rpc_withdraw_labels\x12\x06.label\x1a\x05.null\"\x00(\x01\x12\'\n\x0frpc_pull_labels\x12\x06.label\x1a\x06.label\"\x00(\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_LABEL = _descriptor.Descriptor(
  name='label',
  full_name='label',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label_id', full_name='label.label_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_unicast', full_name='label.is_unicast', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_id', full_name='label.service_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lanzone_id', full_name='label.lanzone_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['label'] = _LABEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

label = _reflection.GeneratedProtocolMessageType('label', (_message.Message,), dict(
  DESCRIPTOR = _LABEL,
  __module__ = 'label_distribution_pb2'
  # @@protoc_insertion_point(class_scope:label)
  ))
_sym_db.RegisterMessage(label)



_LABEL_DISTRIBUTION = _descriptor.ServiceDescriptor(
  name='label_distribution',
  full_name='label_distribution',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=130,
  serialized_end=274,
  methods=[
  _descriptor.MethodDescriptor(
    name='rpc_deposit_labels',
    full_name='label_distribution.rpc_deposit_labels',
    index=0,
    containing_service=None,
    input_type=_LABEL,
    output_type=common__pb2._NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpc_withdraw_labels',
    full_name='label_distribution.rpc_withdraw_labels',
    index=1,
    containing_service=None,
    input_type=_LABEL,
    output_type=common__pb2._NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpc_pull_labels',
    full_name='label_distribution.rpc_pull_labels',
    index=2,
    containing_service=None,
    input_type=_LABEL,
    output_type=_LABEL,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LABEL_DISTRIBUTION)

DESCRIPTOR.services_by_name['label_distribution'] = _LABEL_DISTRIBUTION

# @@protoc_insertion_point(module_scope)
