# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vswitch_lanzone.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vswitch_lanzone.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x15vswitch_lanzone.proto\x1a\x0c\x63ommon.proto\"G\n\x0freq_lanzone_key\x12\x10\n\x08per_uuid\x18\x01 \x01(\x08\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x14\n\x0clanzone_name\x18\x03 \x01(\t\"f\n\x13res_vswitch_lanzone\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tzone_type\x18\x03 \x01(\t\x12\x10\n\x08min_vlan\x18\x04 \x01(\x05\x12\x10\n\x08max_vlan\x18\x05 \x01(\x05\x32\xe9\x02\n\x0fvswitch_lanzone\x12\x43\n\x17rpc_get_vswitch_lanzone\x12\x10.req_lanzone_key\x1a\x14.res_vswitch_lanzone\"\x00\x12I\n\x19rpc_list_vswitch_lanzones\x12\x10.req_lanzone_key\x1a\x14.res_vswitch_lanzone\"\x00(\x01\x30\x01\x12L\n\x1crpc_register_vswitch_lanzone\x12\x14.res_vswitch_lanzone\x1a\x14.res_vswitch_lanzone\"\x00\x12;\n\x1erpc_unregister_vswitch_lanzone\x12\x10.req_lanzone_key\x1a\x05.null\"\x00\x12;\n\x1arpc_update_vswitch_lanzone\x12\x14.res_vswitch_lanzone\x1a\x05.null\"\x00\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_REQ_LANZONE_KEY = _descriptor.Descriptor(
  name='req_lanzone_key',
  full_name='req_lanzone_key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='per_uuid', full_name='req_lanzone_key.per_uuid', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='req_lanzone_key.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lanzone_name', full_name='req_lanzone_key.lanzone_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=110,
)


_RES_VSWITCH_LANZONE = _descriptor.Descriptor(
  name='res_vswitch_lanzone',
  full_name='res_vswitch_lanzone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='res_vswitch_lanzone.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='res_vswitch_lanzone.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zone_type', full_name='res_vswitch_lanzone.zone_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_vlan', full_name='res_vswitch_lanzone.min_vlan', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_vlan', full_name='res_vswitch_lanzone.max_vlan', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=214,
)

DESCRIPTOR.message_types_by_name['req_lanzone_key'] = _REQ_LANZONE_KEY
DESCRIPTOR.message_types_by_name['res_vswitch_lanzone'] = _RES_VSWITCH_LANZONE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

req_lanzone_key = _reflection.GeneratedProtocolMessageType('req_lanzone_key', (_message.Message,), dict(
  DESCRIPTOR = _REQ_LANZONE_KEY,
  __module__ = 'vswitch_lanzone_pb2'
  # @@protoc_insertion_point(class_scope:req_lanzone_key)
  ))
_sym_db.RegisterMessage(req_lanzone_key)

res_vswitch_lanzone = _reflection.GeneratedProtocolMessageType('res_vswitch_lanzone', (_message.Message,), dict(
  DESCRIPTOR = _RES_VSWITCH_LANZONE,
  __module__ = 'vswitch_lanzone_pb2'
  # @@protoc_insertion_point(class_scope:res_vswitch_lanzone)
  ))
_sym_db.RegisterMessage(res_vswitch_lanzone)



_VSWITCH_LANZONE = _descriptor.ServiceDescriptor(
  name='vswitch_lanzone',
  full_name='vswitch_lanzone',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=217,
  serialized_end=578,
  methods=[
  _descriptor.MethodDescriptor(
    name='rpc_get_vswitch_lanzone',
    full_name='vswitch_lanzone.rpc_get_vswitch_lanzone',
    index=0,
    containing_service=None,
    input_type=_REQ_LANZONE_KEY,
    output_type=_RES_VSWITCH_LANZONE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpc_list_vswitch_lanzones',
    full_name='vswitch_lanzone.rpc_list_vswitch_lanzones',
    index=1,
    containing_service=None,
    input_type=_REQ_LANZONE_KEY,
    output_type=_RES_VSWITCH_LANZONE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpc_register_vswitch_lanzone',
    full_name='vswitch_lanzone.rpc_register_vswitch_lanzone',
    index=2,
    containing_service=None,
    input_type=_RES_VSWITCH_LANZONE,
    output_type=_RES_VSWITCH_LANZONE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpc_unregister_vswitch_lanzone',
    full_name='vswitch_lanzone.rpc_unregister_vswitch_lanzone',
    index=3,
    containing_service=None,
    input_type=_REQ_LANZONE_KEY,
    output_type=common__pb2._NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpc_update_vswitch_lanzone',
    full_name='vswitch_lanzone.rpc_update_vswitch_lanzone',
    index=4,
    containing_service=None,
    input_type=_RES_VSWITCH_LANZONE,
    output_type=common__pb2._NULL,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VSWITCH_LANZONE)

DESCRIPTOR.services_by_name['vswitch_lanzone'] = _VSWITCH_LANZONE

# @@protoc_insertion_point(module_scope)
