# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import vswitch_host_pb2 as vswitch__host__pb2


class vswitch_hostStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.rpc_get_vswitch_host = channel.unary_unary(
        '/vswitch_host/rpc_get_vswitch_host',
        request_serializer=vswitch__host__pb2.req_key.SerializeToString,
        response_deserializer=vswitch__host__pb2.res_vswitch_host.FromString,
        )
    self.rpc_list_vswitch_host = channel.stream_stream(
        '/vswitch_host/rpc_list_vswitch_host',
        request_serializer=vswitch__host__pb2.req_key.SerializeToString,
        response_deserializer=vswitch__host__pb2.res_vswitch_host.FromString,
        )
    self.rpc_register_vswiitch_host = channel.unary_unary(
        '/vswitch_host/rpc_register_vswiitch_host',
        request_serializer=vswitch__host__pb2.res_vswitch_host.SerializeToString,
        response_deserializer=vswitch__host__pb2.res_vswitch_host.FromString,
        )
    self.rpc_unregister_vswitch_host = channel.unary_unary(
        '/vswitch_host/rpc_unregister_vswitch_host',
        request_serializer=vswitch__host__pb2.req_key.SerializeToString,
        response_deserializer=vswitch__host__pb2.null.FromString,
        )
    self.rpc_update_vswitch_host = channel.unary_unary(
        '/vswitch_host/rpc_update_vswitch_host',
        request_serializer=vswitch__host__pb2.res_vswitch_host.SerializeToString,
        response_deserializer=vswitch__host__pb2.null.FromString,
        )


class vswitch_hostServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def rpc_get_vswitch_host(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def rpc_list_vswitch_host(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def rpc_register_vswiitch_host(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def rpc_unregister_vswitch_host(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def rpc_update_vswitch_host(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_vswitch_hostServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'rpc_get_vswitch_host': grpc.unary_unary_rpc_method_handler(
          servicer.rpc_get_vswitch_host,
          request_deserializer=vswitch__host__pb2.req_key.FromString,
          response_serializer=vswitch__host__pb2.res_vswitch_host.SerializeToString,
      ),
      'rpc_list_vswitch_host': grpc.stream_stream_rpc_method_handler(
          servicer.rpc_list_vswitch_host,
          request_deserializer=vswitch__host__pb2.req_key.FromString,
          response_serializer=vswitch__host__pb2.res_vswitch_host.SerializeToString,
      ),
      'rpc_register_vswiitch_host': grpc.unary_unary_rpc_method_handler(
          servicer.rpc_register_vswiitch_host,
          request_deserializer=vswitch__host__pb2.res_vswitch_host.FromString,
          response_serializer=vswitch__host__pb2.res_vswitch_host.SerializeToString,
      ),
      'rpc_unregister_vswitch_host': grpc.unary_unary_rpc_method_handler(
          servicer.rpc_unregister_vswitch_host,
          request_deserializer=vswitch__host__pb2.req_key.FromString,
          response_serializer=vswitch__host__pb2.null.SerializeToString,
      ),
      'rpc_update_vswitch_host': grpc.unary_unary_rpc_method_handler(
          servicer.rpc_update_vswitch_host,
          request_deserializer=vswitch__host__pb2.res_vswitch_host.FromString,
          response_serializer=vswitch__host__pb2.null.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'vswitch_host', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
