# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vswitch_interface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vswitch_interface.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x17vswitch_interface.proto\x1a\x0c\x63ommon.proto\"4\n\x11req_interface_key\x12\x11\n\tuuid_type\x18\x01 \x01(\x05\x12\x0c\n\x04uuid\x18\x02 \x01(\t\"\x8f\x01\n\x15res_vswitch_interface\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07host_id\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65v_address\x18\x03 \x01(\t\x12\x18\n\x10interface_status\x18\x04 \x01(\t\x12\x16\n\x0einterface_type\x18\x05 \x01(\t\x12\x12\n\nlanzone_id\x18\x06 \x01(\t2\xaf\x01\n\x11vswitch_interface\x12I\n\x19rpc_get_vswitch_interface\x12\x12.req_interface_key\x1a\x16.res_vswitch_interface\"\x00\x12O\n\x1brpc_list_vswitch_interfaces\x12\x12.req_interface_key\x1a\x16.res_vswitch_interface\"\x00(\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_REQ_INTERFACE_KEY = _descriptor.Descriptor(
  name='req_interface_key',
  full_name='req_interface_key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid_type', full_name='req_interface_key.uuid_type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='req_interface_key.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=93,
)


_RES_VSWITCH_INTERFACE = _descriptor.Descriptor(
  name='res_vswitch_interface',
  full_name='res_vswitch_interface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='res_vswitch_interface.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host_id', full_name='res_vswitch_interface.host_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dev_address', full_name='res_vswitch_interface.dev_address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interface_status', full_name='res_vswitch_interface.interface_status', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interface_type', full_name='res_vswitch_interface.interface_type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lanzone_id', full_name='res_vswitch_interface.lanzone_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=239,
)

DESCRIPTOR.message_types_by_name['req_interface_key'] = _REQ_INTERFACE_KEY
DESCRIPTOR.message_types_by_name['res_vswitch_interface'] = _RES_VSWITCH_INTERFACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

req_interface_key = _reflection.GeneratedProtocolMessageType('req_interface_key', (_message.Message,), dict(
  DESCRIPTOR = _REQ_INTERFACE_KEY,
  __module__ = 'vswitch_interface_pb2'
  # @@protoc_insertion_point(class_scope:req_interface_key)
  ))
_sym_db.RegisterMessage(req_interface_key)

res_vswitch_interface = _reflection.GeneratedProtocolMessageType('res_vswitch_interface', (_message.Message,), dict(
  DESCRIPTOR = _RES_VSWITCH_INTERFACE,
  __module__ = 'vswitch_interface_pb2'
  # @@protoc_insertion_point(class_scope:res_vswitch_interface)
  ))
_sym_db.RegisterMessage(res_vswitch_interface)



_VSWITCH_INTERFACE = _descriptor.ServiceDescriptor(
  name='vswitch_interface',
  full_name='vswitch_interface',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=242,
  serialized_end=417,
  methods=[
  _descriptor.MethodDescriptor(
    name='rpc_get_vswitch_interface',
    full_name='vswitch_interface.rpc_get_vswitch_interface',
    index=0,
    containing_service=None,
    input_type=_REQ_INTERFACE_KEY,
    output_type=_RES_VSWITCH_INTERFACE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpc_list_vswitch_interfaces',
    full_name='vswitch_interface.rpc_list_vswitch_interfaces',
    index=1,
    containing_service=None,
    input_type=_REQ_INTERFACE_KEY,
    output_type=_RES_VSWITCH_INTERFACE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VSWITCH_INTERFACE)

DESCRIPTOR.services_by_name['vswitch_interface'] = _VSWITCH_INTERFACE

# @@protoc_insertion_point(module_scope)
