# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_pb2 as common__pb2
import vswitch_interface_pb2 as vswitch__interface__pb2


class vswitch_interfaceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.rpc_get_vswitch_interface = channel.unary_unary(
        '/vswitch_interface/rpc_get_vswitch_interface',
        request_serializer=vswitch__interface__pb2.req_interface_key.SerializeToString,
        response_deserializer=vswitch__interface__pb2.res_vswitch_interface.FromString,
        )
    self.rpc_list_vswitch_interfaces = channel.stream_stream(
        '/vswitch_interface/rpc_list_vswitch_interfaces',
        request_serializer=vswitch__interface__pb2.req_interface_key.SerializeToString,
        response_deserializer=vswitch__interface__pb2.res_vswitch_interface.FromString,
        )
    self.rpc_update_vswitch_interface = channel.unary_unary(
        '/vswitch_interface/rpc_update_vswitch_interface',
        request_serializer=vswitch__interface__pb2.res_vswitch_interface.SerializeToString,
        response_deserializer=common__pb2.null.FromString,
        )
    self.rpc_register_vswitch_interface = channel.unary_unary(
        '/vswitch_interface/rpc_register_vswitch_interface',
        request_serializer=vswitch__interface__pb2.res_vswitch_interface.SerializeToString,
        response_deserializer=vswitch__interface__pb2.res_vswitch_interface.FromString,
        )
    self.rpc_unregister_vswitch_interface = channel.unary_unary(
        '/vswitch_interface/rpc_unregister_vswitch_interface',
        request_serializer=vswitch__interface__pb2.req_interface_key.SerializeToString,
        response_deserializer=common__pb2.null.FromString,
        )


class vswitch_interfaceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def rpc_get_vswitch_interface(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def rpc_list_vswitch_interfaces(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def rpc_update_vswitch_interface(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def rpc_register_vswitch_interface(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def rpc_unregister_vswitch_interface(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_vswitch_interfaceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'rpc_get_vswitch_interface': grpc.unary_unary_rpc_method_handler(
          servicer.rpc_get_vswitch_interface,
          request_deserializer=vswitch__interface__pb2.req_interface_key.FromString,
          response_serializer=vswitch__interface__pb2.res_vswitch_interface.SerializeToString,
      ),
      'rpc_list_vswitch_interfaces': grpc.stream_stream_rpc_method_handler(
          servicer.rpc_list_vswitch_interfaces,
          request_deserializer=vswitch__interface__pb2.req_interface_key.FromString,
          response_serializer=vswitch__interface__pb2.res_vswitch_interface.SerializeToString,
      ),
      'rpc_update_vswitch_interface': grpc.unary_unary_rpc_method_handler(
          servicer.rpc_update_vswitch_interface,
          request_deserializer=vswitch__interface__pb2.res_vswitch_interface.FromString,
          response_serializer=common__pb2.null.SerializeToString,
      ),
      'rpc_register_vswitch_interface': grpc.unary_unary_rpc_method_handler(
          servicer.rpc_register_vswitch_interface,
          request_deserializer=vswitch__interface__pb2.res_vswitch_interface.FromString,
          response_serializer=vswitch__interface__pb2.res_vswitch_interface.SerializeToString,
      ),
      'rpc_unregister_vswitch_interface': grpc.unary_unary_rpc_method_handler(
          servicer.rpc_unregister_vswitch_interface,
          request_deserializer=vswitch__interface__pb2.req_interface_key.FromString,
          response_serializer=common__pb2.null.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'vswitch_interface', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
