#
#Copyright (c) 2018 Jie Zheng
#
E3VSWITCH_HOST_STATUS_UNKNOWN = 'unknown'
E3VSWITCH_HOST_STATUS_ACTIVE = 'active'
E3VSWITCH_HOST_STATUS_INACTIVE = 'inactive'
E3VSWITCH_HOST_STATUS_MAINTENANCE = 'maintenance'

E3VSWITCH_INTERFACE_STATUS_UNKNOWN = 'unknown'
E3VSWITCH_INTERFACE_STATUS_ACTIVE = 'active'
E3VSWITCH_INTERFACE_STATUS_INACTIVE = 'inactive'
E3VSWITCH_INTERFACE_STATUS_MAINTENANCE = 'maintenance'

E3VSWITCH_INTERFACE_TYPE_SHARED = 'shared'
E3VSWITCH_INTERFACE_TYPE_EXCLUSIVE = 'exclusive'
